addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER={{ github_user }}
  - GITHUB_ORG={{ github_org }}
  - DOCKER_USER={{ docker_user }}
  - DOCKER_ORG={{ docker_org }}
  # DOCKER_PASS
  - secure: "dq5A/0j37SZ71Lb6XbV+QgbDUJv2qSOjt9kC2LOFMiHF/Qbn0CirgJOV9Ze4ctMcoAcNIm8sqzM+q88zHBBscbmysIwyrcHjYAf63RIMHf76nzGtwEspqfBDQMVc67oZPiS7ENGWak3VlelFFNwcEqwnwCYFQ3mmilbRXUzY0taYTyK6hkgnESYxWmFkZEbHe3hSndvp6lcMRBPbLNOBCm9TE4R6rExZClNRipjRHvdeHS0Qr6zpV4dC6Bv9JhNEBbFJKG/9uoHCYclr7vtBu3/ykahLN93fwxNuOVk0+QFQGti7VPEa6JS1MtnmHYjJX9D9kMMHZHLmy/EEfcRcKlIIYUNT3x4KaeVjK2sDE38GFRN5jP6WEDJxZskkei8IRLw7pEoamUWMSyDHfwK1cLQupoWpOCcz4ULAZYJfLRPcyVisfQ5Hu/TqCH7sTQzVdnDtdpYBtC0QA4v41pc2tFVI0ZTpI51dFMMQGU+BNvA5z9CchkJsvpNu8I1OoCTErkRN3Kk3W2W1VxMvuBNr9MmQWHQn6tEZjM4/l/HRaJy5u9yIyOhtu0J3farM098I2d1lFMZbOufxivfofPg4NjaarFQQWlql8aiymg/bARM2+4t+H9qnMk0zVXRNdWjYaQx3cyitCgYbRkoTPUWlH1q1iwHdrxQuK9U09BzedHc="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "e07TZTjQy52EgTThTqx3nWhniyUJQNeQmj3/gew9bfdSpgATr2aAdBlZFeXLjSC1wgtcuATB5rm2dgex83h1OLJpfVbijeX46B3WK1s8NE+7jZXXX5hutzZ+f9Dmh+PFh8EJOakiXXn9j83PeJhotHBO2wGyuQSTcK8Jpf7HC6ACUm9RkV3f5PEVOGobll4haCKFCSddKg34AAPE752b1HHe1sW7hJ2S2ETn/RrIWGZA1Patl6N2TI9Jg2dcMSlwh0BR+IqiH30x8drJ/xeH+K9kjeK+TtH7CiDsm0VCRO+KqHgLKwpIUEXauTI+MOB+/9LNUA//Yv3QzeP/XJ3UpHsZMIfvNw1kmF38PokXDFwL5vjTbi2WDzqY5I34xHABXqYkGqtNs7LLEOrzndEfihdmSQRlp8xORU1JISF/i8yr2GKUwoRiSqMyWTjy67sVmgLkpy6ZkEL3vcDInRNuha4g8UBuj04KQkMuRNAcKGIMnteKcgtCYV0jw3EbglTnjJQdjadWM8J4wZcVSbZA8TQGWhyOmAe3PrkUL5WtjI585B2PqRcsMxMuFniQuwF/MvaqLuu3C2EyxyOya5hpNaSPyjW13jncaRh4BY9et5qsruQW6WFmoqB0Rd1M40Jf97vx6Ieg1BTi3CPSChCN/HmR9McxdLyPS2DsOsxNp8w="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: true

after_success:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
